### ISSUE TITLE
TRPC Caller fails in Dynamic Route

### ISSUE THREAD

**Issue by jackblanc** [t3dotgg/server-actions-trpc-examples#3]
I ran into an issue when using the TRPC caller to fetch data in a Dynamic Route:

Error: Invariant: headers() expects to have requestAsyncStorage, none available. 

<img width="979" alt="Screenshot 2023-11-17 at 9 11 59 PM" src="https://github.com/t3dotgg/server-actions-trpc-examples/assets/15748593/b9f2722a-0ff4-4c90-9f10-bb5cacfd4087">

It seems like the issue is that the `headers()` function only works if it is called within the scope of the RSC. I don't really understand why this is a problem for dynamic routes but not other ("static"?) routes.

I was able to resolve this issue by creating a function `getApiCaller` that returns a new TRPC Caller for each request: 

```
// ~/server/dynamic.ts

import "server-only";

import { auth } from "@clerk/nextjs";
import { headers } from "next/headers";
import { appRouter } from "~/server/api/root";
import { db } from "~/server/db";

export const getApiCaller = () => {
  return appRouter.createCaller({
    headers: headers(),
    auth: auth(),
    db,
  });
};
;
```

And then using this in my Page:

```
export default async function Page({ params }: PageProps) {
  const artistId = z.coerce.number().parse(params.artistId);

  const artist = await getApiCaller().artists.getById({
    id: artistId,
  });

  if (!artist) {
    return (
      <div>
        <h1>Artist not found</h1>
        <Link href={{ pathname: "/artists" }}>View All Artists</Link>
      </div>
    );
  }

  return (
    <div>
      <h1>{artist.name}</h1>
      <p>{artist.genre}</p>
    </div>
  );
}
```

I initially thought that the result of `headers()` would need to be passed in as a parameter from the Page, but it seems like that is not necessary, it just needs to be called on-demand at request time. 

I'm very curious why this is happening and what some better solutions might be. This was quite a frustrating issue to resolve, so hopefully this helps anyone facing this problem!

**Comment by IdoPesok** [comment]
Ran into the same thing!

**Comment by kamityx** [comment]
Same, i'm trying to search to see if I can find a solution, but so far I haven't found anything.

[Next.JS#46356](https://github.com/vercel/next.js/issues/46356)

**Comment by jackblanc** [comment]
This looks related: https://github.com/t3-oss/create-t3-app/issues/1669

**Comment by jackblanc** [comment]
It looks like at build time, the "constant" TRPC caller fails for all routes, so it's not just a problem with dynamic routes. But for some reason it works in dev for non-dynamic routes.

**Comment by jackblanc** [comment]
Fixed in latest version of T3
